//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public Auction()
        {
            this.AuctionRecord = new HashSet<AuctionRecord>();
        }
    
        public int AuctionId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<decimal> HighestBid { get; set; }
        public Nullable<int> Winner { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<AuctionRecord> AuctionRecord { get; set; }
    }
}
